In [3]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
slice1=a[2:6]
print(slice1)

[3 4 5 6]


In [4]:
a=np.array([1,2,3,4,5,6,7,8,9])
slice2=a[::2]
print(slice2)

[1 3 5 7 9]


In [5]:
a=np.array([1,2,3,4,5,6,7,8,9])
reversed=a[::-1]
print(reversed)

[9 8 7 6 5 4 3 2 1]


In [6]:
b=np.array([[1,2,2],[5,0,7],[0,1,2]])
subarray=b[0:2,1:3]
print(subarray)



[[2 2]
 [0 7]]


In [7]:
col=b[:,0]
print(col)

[1 5 0]


In [8]:
row=b[1,:]
print(row)

[5 0 7]


In [9]:
print(b[0,0])
print(b[1,2])

1
7


In [10]:
c=np.array([10,20,30,40,50])
print(c[1])

20


In [11]:
c=np.array([10,20,30,40,50])
print(c[-3])

30


In [12]:
c=np.array([10,20,30,40,50])
print(c[1:4])

[20 30 40]


In [13]:
c=np.array([10,20,30,40,50])
print(c[c>25])

[30 40 50]


a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
r=np.hstack([a1,a2])
print(r)

In [14]:
a1=np.array([[1,2],[3,4]]) 
a2=np.array([[5,6],[7,8]]) 
r=np.hstack([a1,a2]) 
print(r)

[[1 2 5 6]
 [3 4 7 8]]


In [15]:
a1=np.array([[1,2],[3,4]]) 
a2=np.array([[5,6],[7,8]]) 
r=np.vstack([a1,a2]) 
print(r)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [16]:
a1=np.array([[1,2],[3,4]]) 
a2=np.array([[5,6],[7,8]]) 
r=np.dstack([a1,a2]) 
print(r)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [17]:
ar1=np.array([1,2,3,4,5,6])
r=np.split(ar1,3)
print(r)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [20]:
ar1=np.array([1,2,3,4,5])
r=np.array_split(ar1,3)
print(r)

[array([1, 2]), array([3, 4]), array([5])]
