In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print("one dimensional array:",a)

one dimensional array: [1 2 3 4 5]


In [2]:
import numpy as np
a=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print("two dimensional array:",a)    

two dimensional array: [[1 2 3 4 5]
 [2 3 4 5 6]]


In [3]:
import numpy as np
b=np.zeros((2,7))
print("\n array with zeros:\n",b)


 array with zeros:
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
d=np.random.random((7,2))
print("\n array with randow values:\n",d)


 array with randow values:
 [[0.66903327 0.78577716]
 [0.3143498  0.2805661 ]
 [0.65768715 0.05779345]
 [0.00567171 0.07081529]
 [0.4746996  0.68361803]
 [0.5941167  0.79757476]
 [0.63743106 0.58576214]]


In [7]:
import numpy as np
e=np.arange(0,50,5)
print("\n arranged values\n",e)


 arranged values
 [ 0  5 10 15 20 25 30 35 40 45]


In [9]:
import numpy as np
d=np.array([[1,2,3],[4,5,6],[7,8,9],[3,6,9],[7,6,5]])
b=d.reshape(3,5)
print('\n original :\n',d)
print("\n reshaped :\n",b)


 original :
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 6 9]
 [7 6 5]]

 reshaped :
 [[1 2 3 4 5]
 [6 7 8 9 3]
 [6 9 7 6 5]]


In [10]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[7,2,1],[1,8,4]])
print("\nCreated array of 3X5 :\n",a)


Created array of 3X5 :
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 2 1]
 [1 8 4]]


In [11]:
import numpy as np
b=np.zeros((5,3))
print("\narray with 0s:\n",b)


array with 0s:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
import numpy as np
c=np.random.random((5,3))
print("\n Random numbers :\n",c)


 Random numbers :
 [[0.74550281 0.58575229 0.97602268]
 [0.27657675 0.89881724 0.99677835]
 [0.67943086 0.82021437 0.24785542]
 [0.97859342 0.46134489 0.95360831]
 [0.43718222 0.20154383 0.77280516]]


In [13]:
import numpy as np
d=np.arange(0,20,5)
print("\nstep value\n",d)


step value
 [ 0  5 10 15]


In [3]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[7,2,1],[1,8,4]])
b=a.reshape(3,5)
print("\nreshaped to 3x5\n",b)


reshaped to 3x5
 [[1 2 3 4 5]
 [6 7 8 9 7]
 [2 1 1 8 4]]


In [15]:
flat=a.flatten()
print("Flattened array:\n",flat)

Flattened array:
 [1 2 3 4 5 6 7 8 9 7 2 1 1 8 4]


In [16]:
print("\n No of dimensions of array:\n",a.ndim)


 No of dimensions of array:
 2


In [4]:
print("\n Shape of the array: \n",a.shape)


 Shape of the array: 
 (5, 3)


In [5]:
print("\n Arrray element type \n",a.dtype)


 Arrray element type 
 int32


In [8]:
newtype=a.astype('f')
print("\n Covert array element: \n",newtype)
print("\n converted array type: \n",newtype.dtype)


 Covert array element: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [7. 2. 1.]
 [1. 8. 4.]]

 converted array type: 
 float32


In [11]:
size=len(a)
print("\n size of array:\n",a.size)


 size of array:
 15
