In [1]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
x=np.where(arr==6)
print(x)

(array([1, 4], dtype=int64),)


In [10]:
b=np.array((0,1,2,2,7,8,9))
x=np.searchsorted(b,3,side='left')
print(x)

4


In [11]:
b=np.array((0,1,2,2,7,8,9))
x=np.searchsorted(b,8,side='right')
print(x)

6


In [12]:
b=np.array((0,1,2,2,7,8,9))
x=np.searchsorted(b,8,side='left')
print(x)

5


In [15]:
d=np.array([9,5,2,7,6,4])
print(np.sort(d))
e=np.array([[7,4,9],[9,1,4]])
print(np.sort(e))

[2 4 5 6 7 9]
[[4 7 9]
 [1 4 9]]


In [16]:
#boolean=indexing
p=np.array([31,78,69,88])
q=[False,True,False,True]
u=p[q]
print(q)
print(u)

[False, True, False, True]
[78 88]


In [17]:
a=np.array([31,78,69,88])
filter_a=a<70
na=a[filter_a]
print(filter_a)
print(na)

[ True False  True False]
[31 69]
